# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

env:
  DOTNET_VERSION: 7.0.x

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'BestReads.Tests'
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install dependencies
        run: dotnet restore
      - name: Test
        run: |
          dotnet test --logger "trx;LogFileName=results.trx"
          mkdir TestResults-${{ env.DOTNET_VERSION }}
          mv TestResults/results.trx TestResults-${{ env.DOTNET_VERSION }}
      - name: List TestResults
        run: ls -l TestResults-${{ env.DOTNET_VERSION }}
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-results-${{ env.DOTNET_VERSION }}
          path: ${{ github.workspace }}/BestReads.Tests/TestResults-${{ env.DOTNET_VERSION }}
        if: ${{ always() }}

  publish-to-docker:
    needs: [run-unit-tests]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    defaults:
      run:
        working-directory: 'BestReads'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push dotnet image
        uses: docker/build-push-action@v3
        with:
          context: ./BestReads
          push: true 
          tags: augmart/bestreads-extensions